name: elmalaab
description: A new Flutter project.
publish_to: 'none'
version: 1.0.4+4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.3
  image_picker: ^0.8.0+3
  share: ^2.0.4
  font_awesome_flutter: ^9.1.0
  url_launcher: ^6.0.6
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  get_it: ^7.1.3
  dio: ^4.0.0
  flutter_inappwebview: 5.3.2
  firebase_core: ^1.2.1
  firebase_messaging: ^10.0.1
  firebase_dynamic_links: ^2.0.5
  webview_flutter: 0.3.15+1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DINNextLTArabic
      fonts:
        - asset: assets/fonts/DINNextLTArabic-Regular.ttf
        - asset: assets/fonts/DINNextLTArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/DINNextLTArabic-Bold.ttf
          weight: 700
    - family: DINNextLTW23
      fonts:
        - asset: assets/fonts/DINNextLTW23-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
    - family: BeINBlack
      fonts:
        - asset: assets/fonts/BeINBlack-Black.ttf
          weight: 900
